In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [21]:
class SelfAttention(nn.Module):
  def __init__(self,
               embed_dim = 2,
               row_dim = 0,
               col_dim = 1):

    super().__init__()

    self.row_dim = row_dim
    self.col_dim = col_dim

    self.w_q = nn.Linear(in_features=embed_dim, out_features=embed_dim,bias = False)
    self.w_k = nn.Linear(in_features=embed_dim, out_features=embed_dim,bias = False)
    self.w_v = nn.Linear(in_features=embed_dim, out_features=embed_dim,bias = False)



  def forward(self, PE_Embeddings):


    q = self.w_q(PE_Embeddings)   # This is same as PE_Embeddings @ self.w_q.weight.T
    # q = PE_Embeddings @ self.w_q.weight.T
    k = self.w_k(PE_Embeddings)
    v = self.w_v(PE_Embeddings)

    product = torch.matmul(q, k.transpose(dim0 = self.row_dim, dim1 = self.col_dim))
    scaled_product = product/(k.size(self.col_dim)**0.5)
    percents = F.softmax(scaled_product,dim=self.col_dim)
    attention_scores = torch.matmul(percents,v)

    return attention_scores

In [28]:
encodings_matrix = torch.tensor([[1.16, 0.23],
                                 [0.57, 1.36],
                                 [4.41, -2.16]])

torch.manual_seed(100)
at = SelfAttention()
print(at.w_q.weight.shape)
at.forward(encodings_matrix)

torch.Size([2, 2])


tensor([[-0.7496, -1.0678],
        [-0.7556, -1.0467],
        [-0.7457, -0.9820]], grad_fn=<MmBackward0>)

In [31]:

at.forward(encodings_matrix)

tensor([[-0.7496, -1.0678],
        [-0.7556, -1.0467],
        [-0.7457, -0.9820]], grad_fn=<MmBackward0>)

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [37]:
class SelfAttention(nn.Module):
  def __init__(self,
               model_dim = 2,
               row_dim = 0,
               col_dim = 1):
    super().__init__()
    self.row_dim = row_dim
    self.col_dim = col_dim
    self.w_q = nn.Linear(in_features=model_dim,out_features=model_dim, bias = False)
    self.w_k = nn.Linear(in_features=model_dim,out_features=model_dim, bias = False)
    self.w_v = nn.Linear(in_features=model_dim,out_features=model_dim, bias = False)

  def Forward(self, PE_Embeddings):
    q = self.w_q(PE_Embeddings)
    k = self.w_k(PE_Embeddings)
    v = self.w_v(PE_Embeddings)

    similarities = torch.matmul(q,k.transpose(dim0 = self.row_dim, dim1 = self.col_dim))
    scaled_sims = similarities/(torch.tensor(k.size(self.col_dim)**0.5))
    attention_percents = F.softmax(scaled_sims,dim = self.col_dim)
    attention_scores = torch.matmul(attention_percents,v)

    return attention_scores



In [38]:
encodings_matrix = torch.tensor([[1.16, 0.23],
                                 [0.57, 1.36],
                                 [4.41, -2.16]])

torch.manual_seed(42)
selfA = SelfAttention()
print(selfA.Forward(encodings_matrix))

tensor([[1.0100, 1.0641],
        [0.2040, 0.7057],
        [3.4989, 2.2427]], grad_fn=<MmBackward0>)
